# Generated by Django 4.2.30 on 2026-08-06 03:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("ligne_1", models.CharField(max_length=255, verbose_name="Ligne 1")),
                (
                    "ligne_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ligne 2"
                    ),
                ),
                (
                    "point_repere",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Point de repère"
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code postal"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "precision_gps",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXACTE", "Exacte"),
                            ("APPROXIMATIVE", "Approximative"),
                            ("VILLE", "Ville"),
                            ("REGION", "Région"),
                        ],
                        max_length=20,
                        verbose_name="Précision GPS",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
                "ordering": ["country", "region", "city", "district", "neighborhood"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                (
                    "population",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Population"
                    ),
                ),
                (
                    "superficie",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Superficie (km²)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Ville",
                "verbose_name_plural": "Villes",
                "ordering": ["region", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                (
                    "nom_officiel",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom officiel"
                    ),
                ),
                (
                    "code_iso2",
                    models.CharField(
                        max_length=2, unique=True, verbose_name="Code ISO2"
                    ),
                ),
                (
                    "code_iso3",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Code ISO3"
                    ),
                ),
                (
                    "indicatif_telephonique",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Indicatif téléphonique"
                    ),
                ),
                (
                    "devise",
                    models.CharField(blank=True, max_length=10, verbose_name="Devise"),
                ),
                (
                    "langue_principale",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Langue principale"
                    ),
                ),
                (
                    "continent",
                    models.CharField(
                        choices=[
                            ("AF", "Afrique"),
                            ("AS", "Asie"),
                            ("EU", "Europe"),
                            ("NA", "Amérique du Nord"),
                            ("SA", "Amérique du Sud"),
                            ("OC", "Océanie"),
                            ("AN", "Antarctique"),
                        ],
                        max_length=2,
                        verbose_name="Continent",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Pays",
                "verbose_name_plural": "Pays",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "ville",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="locations.city",
                        verbose_name="Ville",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arrondissement",
                "verbose_name_plural": "Arrondissements",
                "ordering": ["ville", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="locations.country",
                        verbose_name="Pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Région",
                "verbose_name_plural": "Régions",
                "ordering": ["country", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code postal"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "niveau_securite",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRES_HAUT", "Très haut"),
                            ("HAUT", "Haut"),
                            ("MOYEN", "Moyen"),
                            ("BAS", "Bas"),
                            ("TRES_BAS", "Très bas"),
                        ],
                        max_length=20,
                        verbose_name="Niveau de sécurité",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighborhoods",
                        to="locations.district",
                        verbose_name="Arrondissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quartier",
                "verbose_name_plural": "Quartiers",
                "ordering": ["district", "nom"],
            },
        ),
        migrations.CreateModel(
            name="GeoLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitude"
                    ),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Altitude (m)",
                    ),
                ),
                (
                    "precision",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Précision (m)",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("GPS", "GPS"),
                            ("IP", "Adresse IP"),
                            ("WIFI", "WiFi"),
                            ("MANUEL", "Manuel"),
                            ("API", "API externe"),
                        ],
                        default="GPS",
                        max_length=20,
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "date_mise_a_jour",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Géolocalisation",
                "verbose_name_plural": "Géolocalisations",
                "ordering": ["-date_mise_a_jour"],
                "indexes": [
                    models.Index(
                        fields=["latitude"], name="locations_g_latitud_9bd8a9_idx"
                    ),
                    models.Index(
                        fields=["longitude"], name="locations_g_longitu_f3765a_idx"
                    ),
                    models.Index(
                        fields=["provider"], name="locations_g_provide_22b5ff_idx"
                    ),
                    models.Index(
                        fields=["date_mise_a_jour"],
                        name="locations_g_date_mi_01b4f2_idx",
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="locations_g_latitud_7828fb_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(fields=["nom"], name="locations_c_nom_955e7d_idx"),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(
                fields=["code_iso2"], name="locations_c_code_is_da6b6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(
                fields=["code_iso3"], name="locations_c_code_is_5c61f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(
                fields=["continent"], name="locations_c_contine_f7e759_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(fields=["actif"], name="locations_c_actif_c11c8a_idx"),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("nom",),
                name="unique_country_nom",
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code_iso2",),
                name="unique_country_iso2",
            ),
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code_iso3",),
                name="unique_country_iso3",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="locations.region",
                verbose_name="Région",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addresses",
                to="locations.city",
                verbose_name="Ville",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="addresses",
                to="locations.country",
                verbose_name="Pays",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addresses",
                to="locations.district",
                verbose_name="Arrondissement",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addresses",
                to="locations.neighborhood",
                verbose_name="Quartier",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addresses",
                to="locations.region",
                verbose_name="Région",
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(fields=["nom"], name="locations_r_nom_d62fb1_idx"),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(fields=["code"], name="locations_r_code_975e29_idx"),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                fields=["country"], name="locations_r_country_477eb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(
                fields=["country", "nom"], name="locations_r_country_4f0328_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("country", "code"),
                name="unique_region_country_code",
            ),
        ),
        migrations.AddIndex(
            model_name="neighborhood",
            index=models.Index(fields=["nom"], name="locations_n_nom_602d9c_idx"),
        ),
        migrations.AddIndex(
            model_name="neighborhood",
            index=models.Index(
                fields=["district"], name="locations_n_distric_3507eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="neighborhood",
            index=models.Index(
                fields=["code_postal"], name="locations_n_code_po_82543a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="neighborhood",
            index=models.Index(
                fields=["niveau_securite"], name="locations_n_niveau__c7cad4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="neighborhood",
            index=models.Index(
                fields=["district", "nom"], name="locations_n_distric_cf01d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(fields=["nom"], name="locations_d_nom_bf5580_idx"),
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(fields=["ville"], name="locations_d_ville_i_20da32_idx"),
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(
                fields=["ville", "nom"], name="locations_d_ville_i_13b1a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["nom"], name="locations_c_nom_ee18d8_idx"),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["code"], name="locations_c_code_593a72_idx"),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["region"], name="locations_c_region__f92127_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["latitude"], name="locations_c_latitud_611190_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["longitude"], name="locations_c_longitu_3b3f23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["actif"], name="locations_c_actif_1b4f59_idx"),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["region", "nom"], name="locations_c_region__602af2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("region", "code"),
                name="unique_city_region_code",
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["country"], name="locations_a_country_30335b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["region"], name="locations_a_region__51f614_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["city"], name="locations_a_city_id_119ce4_idx"),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["district"], name="locations_a_distric_85fb77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["neighborhood"], name="locations_a_neighbo_59f5f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["latitude"], name="locations_a_latitud_162a04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["longitude"], name="locations_a_longitu_622ac4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["code_postal"], name="locations_a_code_po_62c8bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["city", "district"], name="locations_a_city_id_21b9dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["neighborhood", "code_postal"],
                name="locations_a_neighbo_8d8570_idx",
            ),
        ),
    ]
