# Generated by Django 4.2.30 on 2026-08-07 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Appartement"),
                            ("HOUSE", "Maison"),
                            ("STUDIO", "Studio"),
                            ("LOFT", "Loft"),
                            ("VILLA", "Villa"),
                            ("TERRACE", "Terasse"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de logement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PUBLISHED", "Publié"),
                            ("RENTED", "Loué"),
                            ("SUSPENDED", "Suspendu"),
                            ("ARCHIVED", "Archivé"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "rent_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix du loyer"
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Charges",
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Caution",
                    ),
                ),
                (
                    "surface",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Surface (m²)"
                    ),
                ),
                ("rooms", models.IntegerField(verbose_name="Nombre de pièces")),
                (
                    "bedrooms",
                    models.IntegerField(default=0, verbose_name="Nombre de chambres"),
                ),
                (
                    "bathrooms",
                    models.IntegerField(
                        default=0, verbose_name="Nombre de salles de bain"
                    ),
                ),
                (
                    "floor",
                    models.IntegerField(blank=True, null=True, verbose_name="Étage"),
                ),
                (
                    "furnished",
                    models.BooleanField(default=False, verbose_name="Meublé"),
                ),
                ("parking", models.BooleanField(default=False, verbose_name="Parking")),
                ("balcony", models.BooleanField(default=False, verbose_name="Balcon")),
                ("terrace", models.BooleanField(default=False, verbose_name="Terasse")),
                (
                    "elevator",
                    models.BooleanField(default=False, verbose_name="Ascenseur"),
                ),
                ("garden", models.BooleanField(default=False, verbose_name="Jardin")),
                ("pool", models.BooleanField(default=False, verbose_name="Piscine")),
                (
                    "air_conditioning",
                    models.BooleanField(default=False, verbose_name="Climatisation"),
                ),
                (
                    "heating",
                    models.BooleanField(default=False, verbose_name="Chauffage"),
                ),
                (
                    "available_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Disponible à partir du"
                    ),
                ),
                (
                    "minimum_rent_duration",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Durée minimale de location (mois)",
                    ),
                ),
                (
                    "main_photo",
                    models.URLField(
                        blank=True, null=True, verbose_name="Photo principale"
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(default=0, verbose_name="Nombre de vues"),
                ),
                (
                    "inquiries_count",
                    models.IntegerField(default=0, verbose_name="Nombre de demandes"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="properties",
                        to="locations.address",
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logement",
                "verbose_name_plural": "Logements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["landlord"], name="listings_pr_landlor_1f4bf9_idx"
                    ),
                    models.Index(
                        fields=["status"], name="listings_pr_status_de90a3_idx"
                    ),
                    models.Index(
                        fields=["property_type"], name="listings_pr_propert_36edbb_idx"
                    ),
                    models.Index(
                        fields=["rent_price"], name="listings_pr_rent_pr_d707c3_idx"
                    ),
                    models.Index(
                        fields=["available_from"], name="listings_pr_availab_23459f_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="listings_pr_created_e6aabb_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("landlord", "title"),
                name="unique_landlord_property_title",
            ),
        ),
    ]
