# Generated by Django 4.2.30 on 2026-08-12 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "cloudinary_public_id",
                    models.CharField(
                        max_length=255, verbose_name="Public ID Cloudinary"
                    ),
                ),
                (
                    "secure_url",
                    models.URLField(
                        max_length=500, verbose_name="URL sécurisée Cloudinary"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Vidéo")],
                        default="image",
                        max_length=10,
                        verbose_name="Type de ressource",
                    ),
                ),
                (
                    "format",
                    models.CharField(blank=True, max_length=20, verbose_name="Format"),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Largeur (px)"
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Hauteur (px)"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Durée (secondes)"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Taille du fichier (octets)"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Média principal"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="listings.property",
                        verbose_name="Logement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média du logement",
                "verbose_name_plural": "Médias des logements",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["property"], name="listings_pr_propert_aef214_idx"
                    ),
                    models.Index(
                        fields=["resource_type"], name="listings_pr_resourc_5d3140_idx"
                    ),
                    models.Index(
                        fields=["is_primary"], name="listings_pr_is_prim_3bb54f_idx"
                    ),
                    models.Index(fields=["order"], name="listings_pr_order_edb647_idx"),
                ],
            },
        ),
    ]
