# Generated by Django 4.2.30 on 2026-08-11 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("requested_date", models.DateField(verbose_name="Date demandée")),
                ("requested_time", models.TimeField(verbose_name="Heure demandée")),
                (
                    "message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Message du client"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Acceptée"),
                            ("REJECTED", "Refusée"),
                            ("RESCHEDULED", "Reprogrammée"),
                            ("CANCELLED", "Annulée"),
                            ("COMPLETED", "Terminée"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "landlord_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Réponse du bailleur"
                    ),
                ),
                (
                    "rescheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date reprogrammée"
                    ),
                ),
                (
                    "rescheduled_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure reprogrammée"
                    ),
                ),
                (
                    "rescheduled_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Message de reprogrammation"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Client",
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bailleur",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="listings.property",
                        verbose_name="Logement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visite",
                "verbose_name_plural": "Visites",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["property"], name="visits_visi_propert_b99e42_idx"
                    ),
                    models.Index(
                        fields=["client"], name="visits_visi_client__f14875_idx"
                    ),
                    models.Index(
                        fields=["landlord"], name="visits_visi_landlor_daaa8e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="visits_visi_status_ae8d13_idx"
                    ),
                    models.Index(
                        fields=["requested_date"], name="visits_visi_request_ab99ae_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="visits_visi_created_2e9076_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("property", "client", "requested_date", "requested_time"),
                name="unique_pending_visit_request",
            ),
        ),
    ]
