# Generated by Django 4.2.30 on 2026-08-06 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "nom",
                    models.CharField(blank=True, max_length=100, verbose_name="Nom"),
                ),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=100, verbose_name="Prénom"),
                ),
                ("photo", models.URLField(blank=True, null=True, verbose_name="Photo")),
                (
                    "date_naissance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin"), ("A", "Autre")],
                        max_length=1,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "langue",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "Anglais"),
                            ("es", "Espagnol"),
                            ("de", "Allemand"),
                            ("pt", "Portugais"),
                        ],
                        default="fr",
                        max_length=5,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "etat_compte",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("INACTIF", "Inactif"),
                            ("SUSPENDU", "Suspendu"),
                            ("BLOQUE", "Bloqué"),
                            ("EN_ATTENTE", "En attente"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                        verbose_name="État du compte",
                    ),
                ),
                (
                    "email_verifie",
                    models.BooleanField(default=False, verbose_name="Email vérifié"),
                ),
                (
                    "telephone_verifie",
                    models.BooleanField(
                        default=False, verbose_name="Téléphone vérifié"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False, verbose_name="Super utilisateur"
                    ),
                ),
                (
                    "derniere_connexion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière connexion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email tenté"
                    ),
                ),
                ("adresse_ip", models.GenericIPAddressField(verbose_name="Adresse IP")),
                (
                    "navigateur",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Navigateur"
                    ),
                ),
                ("os", models.CharField(blank=True, max_length=100, verbose_name="OS")),
                (
                    "appareil",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Appareil"
                    ),
                ),
                (
                    "resultat",
                    models.CharField(
                        choices=[("SUCCES", "Succès"), ("ECHEC", "Échec")],
                        max_length=20,
                        verbose_name="Résultat",
                    ),
                ),
                (
                    "raison_echec",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAUVAIS_EMAIL", "Email incorrect"),
                            ("MAUVAIS_MOT_DE_PASSE", "Mot de passe incorrect"),
                            ("COMPTE_INACTIF", "Compte inactif"),
                            ("COMPTE_BLOQUE", "Compte bloqué"),
                            ("COMPTE_SUSPENDU", "Compte suspendu"),
                            ("EMAIL_NON_VERIFIE", "Email non vérifié"),
                            ("TELEPHONE_NON_VERIFIE", "Téléphone non vérifié"),
                            ("TENTATIVES_EXCESSIVES", "Tentatives excessives"),
                            ("TOKEN_EXPIRE", "Token expiré"),
                            ("TOKEN_INVALIDE", "Token invalide"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Raison de l'échec",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
            ],
            options={
                "verbose_name": "Historique de connexion",
                "verbose_name_plural": "Historiques de connexions",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="Code"),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("module", models.CharField(max_length=50, verbose_name="Module")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "ordering": ["module", "code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "niveau_priorite",
                    models.IntegerField(default=0, verbose_name="Niveau de priorité"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="accounts.permission",
                        verbose_name="Permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle",
                "verbose_name_plural": "Rôles",
                "ordering": ["-niveau_priorite", "nom"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=255, unique=True, verbose_name="Token"),
                ),
                (
                    "refresh_token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Refresh token"
                    ),
                ),
                ("adresse_ip", models.GenericIPAddressField(verbose_name="Adresse IP")),
                (
                    "navigateur",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Navigateur"
                    ),
                ),
                (
                    "systeme",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Système"
                    ),
                ),
                (
                    "appareil",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Appareil"
                    ),
                ),
                (
                    "date_connexion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de connexion"
                    ),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(verbose_name="Date d'expiration"),
                ),
                (
                    "est_active",
                    models.BooleanField(default=True, verbose_name="Active"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session utilisateur",
                "verbose_name_plural": "Sessions utilisateurs",
                "ordering": ["-date_connexion"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "date_attribution",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'attribution"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "attribue_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_attribues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Attribué par",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="accounts.role",
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle utilisateur",
                "verbose_name_plural": "Rôles utilisateurs",
                "ordering": ["-date_attribution"],
            },
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=255, unique=True, verbose_name="Token"),
                ),
                ("expiration", models.DateTimeField(verbose_name="Date d'expiration")),
                ("revoque", models.BooleanField(default=False, verbose_name="Révoqué")),
                (
                    "date_revoquation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de révocation"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="accounts.usersession",
                        verbose_name="Session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refresh token",
                "verbose_name_plural": "Refresh tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["code"], name="accounts_pe_code_3a265a_idx"),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["module"], name="accounts_pe_module_1658a5_idx"),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["active"], name="accounts_pe_active_705108_idx"),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["module", "code"], name="accounts_pe_module_97746a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="permission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="unique_permission_code",
            ),
        ),
        migrations.AddField(
            model_name="loginhistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="login_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["token"], name="accounts_us_token_0e98df_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["refresh_token"], name="accounts_us_refresh_c11c5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(fields=["user"], name="accounts_us_user_id_691a59_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["est_active"], name="accounts_us_est_act_f92ba5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["date_expiration"], name="accounts_us_date_ex_15bc49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["adresse_ip"], name="accounts_us_adresse_7899b8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usersession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("token",),
                name="unique_session_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="usersession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("refresh_token",),
                name="unique_session_refresh_token",
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "role"], name="accounts_us_user_id_5c3bd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["role"], name="accounts_us_role_id_3b7362_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["actif"], name="accounts_us_actif_4ca195_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["date_attribution"], name="accounts_us_date_at_a72d3e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["code"], name="accounts_ro_code_5aeee6_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["actif"], name="accounts_ro_actif_fdb3c9_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["niveau_priorite"], name="accounts_ro_niveau__29e01e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="unique_role_code",
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["token"], name="accounts_re_token_cb0fbf_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["user"], name="accounts_re_user_id_8305ee_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["session"], name="accounts_re_session_0736a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["expiration"], name="accounts_re_expirat_b4fa27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["revoque"], name="accounts_re_revoque_0f00b0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("token",),
                name="unique_refresh_token",
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(fields=["user"], name="accounts_lo_user_id_b24570_idx"),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(fields=["email"], name="accounts_lo_email_70d4ae_idx"),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["adresse_ip"], name="accounts_lo_adresse_33ffae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["resultat"], name="accounts_lo_resulta_4fdf01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(fields=["date"], name="accounts_lo_date_721889_idx"),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["user", "date"], name="accounts_lo_user_id_875f37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["adresse_ip", "date"], name="accounts_lo_adresse_f32cb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="accounts_cu_email_5ce40b_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["telephone"], name="accounts_cu_telepho_1892aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["etat_compte"], name="accounts_cu_etat_co_86d888_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["email_verifie", "telephone_verifie"],
                name="accounts_cu_email_v_0bf24a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["derniere_connexion"], name="accounts_cu_dernier_9e5bb8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("email",),
                name="unique_email_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("telephone",),
                name="unique_telephone_active",
            ),
        ),
    ]
