# Generated by Django 4.2.30 on 2026-08-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="refresh_token",
            field=models.CharField(
                max_length=500, unique=True, verbose_name="Refresh token"
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="token",
            field=models.CharField(max_length=500, unique=True, verbose_name="Token"),
        ),
    ]
