# Generated by Django 4.2.30 on 2026-08-06 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("twitter", models.URLField(blank=True, verbose_name="Twitter")),
                ("tiktok", models.URLField(blank=True, verbose_name="TikTok")),
                ("youtube", models.URLField(blank=True, verbose_name="YouTube")),
                ("site_web", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien social",
                "verbose_name_plural": "Liens sociaux",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandlordProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom_affichage",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom d'affichage"
                    ),
                ),
                (
                    "type_bailleur",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PARTICULIER", "Particulier"),
                            ("PROFESSIONNEL", "Professionnel"),
                            ("AGENCE", "Agence"),
                            ("ENTREPRISE", "Entreprise"),
                        ],
                        max_length=20,
                        verbose_name="Type de bailleur",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "annees_experience",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Années d'expérience"
                    ),
                ),
                (
                    "nombre_logements",
                    models.IntegerField(default=0, verbose_name="Nombre de logements"),
                ),
                (
                    "score_confiance",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Score de confiance"
                    ),
                ),
                (
                    "note_moyenne",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Note moyenne",
                    ),
                ),
                (
                    "taux_reponse",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Taux de réponse (%)",
                    ),
                ),
                (
                    "temps_reponse_moyen",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Temps de réponse moyen (minutes)",
                    ),
                ),
                (
                    "est_certifie",
                    models.BooleanField(default=False, verbose_name="Certifié"),
                ),
                (
                    "date_certification",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de certification"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landlord_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil bailleur",
                "verbose_name_plural": "Profils bailleurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IdentityDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("CARTE_IDENTITE", "Carte d'identité"),
                            ("PASSEPORT", "Passeport"),
                            ("PERMIS_CONDUIRE", "Permis de conduire"),
                            ("CARTE_SEJOUR", "Carte de séjour"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                ("numero", models.CharField(max_length=100, verbose_name="Numéro")),
                (
                    "date_expiration",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                ("document_recto", models.URLField(verbose_name="Document recto")),
                (
                    "document_verso",
                    models.URLField(
                        blank=True, null=True, verbose_name="Document verso"
                    ),
                ),
                (
                    "selfie_verification",
                    models.URLField(
                        blank=True, null=True, verbose_name="Selfie de vérification"
                    ),
                ),
                (
                    "etat_verification",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("EN_COURS", "En cours"),
                            ("VERIFIE", "Vérifié"),
                            ("REFUSE", "Refusé"),
                            ("EXPIRE", "Expiré"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                        verbose_name="État de vérification",
                    ),
                ),
                (
                    "date_verification",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de vérification"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "verifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_verifies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vérifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document d'identité",
                "verbose_name_plural": "Documents d'identité",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "lien_parente",
                    models.CharField(
                        choices=[
                            ("CONJOINT", "Conjoint"),
                            ("PERE", "Père"),
                            ("MERE", "Mère"),
                            ("FRERE", "Frère"),
                            ("SOEUR", "Sœur"),
                            ("AMI", "Ami"),
                            ("COLLEGUE", "Collègue"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Lien de parenté",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact d'urgence",
                "verbose_name_plural": "Contacts d'urgence",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profession"
                    ),
                ),
                (
                    "revenu_estime",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Revenu estimé",
                    ),
                ),
                (
                    "preferences_recherche",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Préférences de recherche"
                    ),
                ),
                (
                    "historique_locations",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Historique des locations"
                    ),
                ),
                (
                    "nombre_favoris",
                    models.IntegerField(default=0, verbose_name="Nombre de favoris"),
                ),
                (
                    "nombre_visites",
                    models.IntegerField(default=0, verbose_name="Nombre de visites"),
                ),
                (
                    "note_moyenne",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Note moyenne",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil client",
                "verbose_name_plural": "Profils clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "nom_banque",
                    models.CharField(max_length=100, verbose_name="Nom de la banque"),
                ),
                (
                    "titulaire",
                    models.CharField(
                        max_length=100, verbose_name="Titulaire du compte"
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
                ),
                (
                    "bic",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="BIC/SWIFT"
                    ),
                ),
                (
                    "numero_compte",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Numéro de compte"
                    ),
                ),
                (
                    "mobile_money",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Mobile Money"
                    ),
                ),
                (
                    "numero_mobile_money",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numéro Mobile Money"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte bancaire",
                "verbose_name_plural": "Comptes bancaires",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                (
                    "fonction",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fonction"
                    ),
                ),
                (
                    "departement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Département"
                    ),
                ),
                (
                    "niveau_acces",
                    models.CharField(
                        choices=[
                            ("LECTURE", "Lecture seule"),
                            ("STANDARD", "Standard"),
                            ("AVANCE", "Avancé"),
                            ("SUPERVISEUR", "Superviseur"),
                            ("COMPLET", "Accès complet"),
                        ],
                        default="STANDARD",
                        max_length=20,
                        verbose_name="Niveau d'accès",
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Signature"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil administrateur",
                "verbose_name_plural": "Profils administrateurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Supprimé"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de suppression"
                    ),
                ),
                ("photo", models.URLField(blank=True, null=True, verbose_name="Photo")),
                (
                    "date_naissance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin"), ("A", "Autre")],
                        max_length=1,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "langue",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "Anglais"),
                            ("es", "Espagnol"),
                            ("de", "Allemand"),
                            ("pt", "Portugais"),
                        ],
                        default="fr",
                        max_length=5,
                        verbose_name="Langue",
                    ),
                ),
                ("biographie", models.TextField(blank=True, verbose_name="Biographie")),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profession"
                    ),
                ),
                (
                    "nationalite",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nationalité"
                    ),
                ),
                (
                    "photo_couverture",
                    models.URLField(
                        blank=True, null=True, verbose_name="Photo de couverture"
                    ),
                ),
                ("site_web", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "etat_profil",
                    models.CharField(
                        choices=[
                            ("INCOMPLET", "Incomplet"),
                            ("COMPLET", "Complet"),
                            ("EN_REVISION", "En révision"),
                            ("VERIFIE", "Vérifié"),
                            ("SUSPENDU", "Suspendu"),
                        ],
                        default="INCOMPLET",
                        max_length=20,
                        verbose_name="État du profil",
                    ),
                ),
                (
                    "est_verifie",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "derniere_activite",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière activité"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="profiles_us_user_id_65af30_idx"
                    ),
                    models.Index(
                        fields=["etat_profil"], name="profiles_us_etat_pr_5b6b13_idx"
                    ),
                    models.Index(
                        fields=["est_verifie"], name="profiles_us_est_ver_a0422e_idx"
                    ),
                    models.Index(
                        fields=["derniere_activite"],
                        name="profiles_us_dernier_1dfd5b_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user",),
                name="unique_user_profile",
            ),
        ),
        migrations.AddIndex(
            model_name="sociallink",
            index=models.Index(fields=["user"], name="profiles_so_user_id_4c4ef3_idx"),
        ),
        migrations.AddConstraint(
            model_name="sociallink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user",),
                name="unique_social_link",
            ),
        ),
        migrations.AddIndex(
            model_name="landlordprofile",
            index=models.Index(fields=["user"], name="profiles_la_user_id_e53013_idx"),
        ),
        migrations.AddIndex(
            model_name="landlordprofile",
            index=models.Index(
                fields=["type_bailleur"], name="profiles_la_type_ba_65696d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landlordprofile",
            index=models.Index(
                fields=["est_certifie"], name="profiles_la_est_cer_e05168_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landlordprofile",
            index=models.Index(
                fields=["note_moyenne"], name="profiles_la_note_mo_03699f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landlordprofile",
            index=models.Index(
                fields=["score_confiance"], name="profiles_la_score_c_d03b7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="landlordprofile",
            index=models.Index(
                fields=["nombre_logements"], name="profiles_la_nombre__f12f6b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="landlordprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user",),
                name="unique_landlord_profile",
            ),
        ),
        migrations.AddIndex(
            model_name="identitydocument",
            index=models.Index(fields=["user"], name="profiles_id_user_id_87434c_idx"),
        ),
        migrations.AddIndex(
            model_name="identitydocument",
            index=models.Index(
                fields=["type_document"], name="profiles_id_type_do_26b986_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identitydocument",
            index=models.Index(
                fields=["etat_verification"], name="profiles_id_etat_ve_71173c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identitydocument",
            index=models.Index(
                fields=["date_expiration"], name="profiles_id_date_ex_0ba7f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(fields=["user"], name="profiles_em_user_id_6f0813_idx"),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(
                fields=["telephone"], name="profiles_em_telepho_8d92fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientprofile",
            index=models.Index(fields=["user"], name="profiles_cl_user_id_8ca3ca_idx"),
        ),
        migrations.AddIndex(
            model_name="clientprofile",
            index=models.Index(
                fields=["note_moyenne"], name="profiles_cl_note_mo_70e085_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientprofile",
            index=models.Index(
                fields=["nombre_favoris"], name="profiles_cl_nombre__fec52d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientprofile",
            index=models.Index(
                fields=["nombre_visites"], name="profiles_cl_nombre__6cdc2a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user",),
                name="unique_client_profile",
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(fields=["user"], name="profiles_ba_user_id_af2e14_idx"),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(fields=["iban"], name="profiles_ba_iban_efb64f_idx"),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["numero_compte"], name="profiles_ba_numero__0b0f12_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("iban",),
                name="unique_iban",
            ),
        ),
        migrations.AddIndex(
            model_name="adminprofile",
            index=models.Index(fields=["user"], name="profiles_ad_user_id_eda9b6_idx"),
        ),
        migrations.AddIndex(
            model_name="adminprofile",
            index=models.Index(
                fields=["departement"], name="profiles_ad_departe_64f636_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminprofile",
            index=models.Index(
                fields=["niveau_acces"], name="profiles_ad_niveau__317680_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="adminprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user",),
                name="unique_admin_profile",
            ),
        ),
    ]
