# Generated by Django 4.2.30 on 2026-08-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="photo_cloudinary_public_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Cloudinary Public ID Photo",
            ),
        ),
    ]
